### ISSUE TITLE
Several issues on first use.

### ISSUE THREAD

**Issue by 2No2Name** [Earthcomputer/MusicalCode#1]
First of all thank you for writing this amazing tool.
I had some small issues when first using musical code, (if you want me to, I will split this into several issues):

1. It was unclear to me in the readme where the mucial-config.txt is expected to be by default, but the --stacktrace argument helped out: It is expected in the project root.

2. The example config line `net/minecraft/client/MinecraftClient/*   # Listens for changes in all members inside Screen` causes the program to crash for me when running `./gradlew musicalCodeTask --from 1.16 --to 1.16.1 --stacktrace`. `What went wrong:
Execution failed for task ':musicalCodeTask'.
> net/minecraft/client/MinecraftClient/* does not match the pattern for class names`
https://pastebin.com/qGPdcv5L

Replacing the /* with .* made it not crash, but that makes it listen for methods instead of fields.

3. The program outputs a list of changed methods in MinecraftClient after doing 2.
However the other example lines lead to the output `Field net/minecraft/class_2369.SHAPE not found`
`Method net/minecraft/class_329.renderCrosshair(Lnet/minecraft/class_4587;)V not found`
. I believe this is due to SHAPE not being remapped to field_11106 for some reason. Similarly for renderCrosshair.

4. Furthermore it is unclear to me whether the names in the config file must be written in the mappings of the --from version or the --to version. From the output `Downloading yarn-1.16.1+build.20.jar...` I would guess it is the --to version

**Comment by Earthcomputer** [comment]
1) and 2) were problems with the readme, they have now been fixed.
3) you were right about the cause, it's now been fixed.
4) the gradle plugin takes the yarn version from loom, so it's the version you specify using the `mappings` configuration in your `dependencies` block. The standalone version takes the yarn version from the `--yarn` argument, and defaults to intermediary (no yarn) if absent.

A new version, 1.1, has been released.
